# config/settings.py

# Forex symbols and timeframes
SYMBOLS = ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD"]

# Indicator parameters
SMA_WINDOWS = [10, 20, 50]
RSI_WINDOW = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
LIQUIDITY_LOOKBACK = 20
ORDER_BLOCKS_LOOKBACK = 50
ORDER_BLOCKS_THRESHOLD = 0.01